### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by yuanzhongfei** [Rick-Cai/LightGCL#1]
你好，我看代码实现里面好像损失函数没有正则化哪一项，是不是少写了

**Comment by Rick-Cai** [comment]
你好，谢谢关注我们的工作。正则项在PyTorch中是在Optimizer里自动实现的，由optimizer = torch.optim.Adam(model.parameters(),weight_decay=lambda_2,lr=lr) 这一行里面的"weight_decay"参数控制，其数值就是L2正则的系数。

**Comment by yuanzhongfei** [comment]
好的 谢谢
