### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by kbk12** [Rick-Cai/LightGCL#2]
你好，请问一下你加载的数据集trnMat.pkl和tstMat.pkl，打印出来是这种（22408，10997） 1.0  ，是怎么生成的这种格式，可以提供一下代码吗

**Comment by Rick-Cai** [comment]
[makeDatasets.zip](https://github.com/Rick-Cai/LightGCL/files/10074656/makeDatasets.zip)
你好，谢谢关注我们的工作。数据集的格式是[scipy.sparse.coo_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html)，可以调用scipy库的构造函数生成。我们处理数据集的代码请见附件，首先在raw data上运行dataProcess.py生成leave_one_out形式的数据，再接着运行makeData.py来生成7:1:2的数据集。
