### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by yuanzhongfei** [Rick-Cai/LightGCL#3]
你好，关于前几天问你的一个代码问题还有点不太理解。optimizer = torch.optim.Adam(model.parameters(),weight_decay=lambda_2,lr=lr)这个weight_decay是衰减因子吧，但是损失函数里并没有正则项（防止过拟合的那一项损失），我查了网上也没有详细的说明。这有点不太理解，谢谢

**Comment by Rick-Cai** [comment]
https://pytorch.org/docs/stable/generated/torch.optim.Adam.html?highlight=adam#torch.optim.Adam
![图片](https://user-images.githubusercontent.com/60952950/203940540-e6a1b799-dfdd-4148-8691-1257c811bcf3.png)
weight_decay即是正则项的系数，正则项是在optimizer内部实现的，只需要设定其系数即可。L2正则起作用的方式本身就是在每一轮将参数减小（即衰减）。

**Comment by yuanzhongfei** [comment]
非常感谢
