### ISSUE TITLE
refer

### ISSUE THREAD

**Issue by Iwillcome** [Rick-Cai/LightGCL#5]
Dear Author:
    Thanks! I am ready to refer to this paper, But it is still unpublish by any publisher. So I want to ask whether It will be published in ArXiv.
   Best Wish!

**Comment by Rick-Cai** [comment]
Thanks for reading and referring to our paper! The paper has just been accepted by ICLR 2023. We are still making final adjustments and polishment to the manuscript. We expect to upload the final version to Arxiv within two weeks. Thank you!

**Comment by Rick-Cai** [comment]
Hi Iwillcome, we have just uploaded our camera-ready version of the paper to Arxiv. Here's the link: [link](https://arxiv.org/abs/2302.08191). Sorry for the long delay, as we have been revising and polishing the draft and codes in the past weeks for better usage. Thanks for your attention in our work and good luck on your submission!

**Comment by Rick-Cai** [comment]
And in fact, the openreview page of the paper can be found in Google Scholar now: [Google Scholar](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=simple+yet+effective+graph+contrastive+learning&btnG=). And if you don't mind, we would prefer citation as follows:

@inproceedings{caisimple,
  title={Simple Yet Effective Graph Contrastive Learning for Recommendation},
  author={Cai, Xuheng and Huang, Chao and Xia, Lianghao and Ren, Xubin},
  booktitle={International Conference on Learning Representations}
}

Thank you!
